In [1]:
import numpy as np
import pandas as  pd
import statsmodels.api as sm
import matplotlib.pyplot as plt

In [2]:
np.random.seed(123)

In [3]:
nsample = 50
x1 = np.linspace(1,10,nsample)
x2= np.sqrt(x1)

In [4]:
x1[:5]

array([1.        , 1.18367347, 1.36734694, 1.55102041, 1.73469388])

In [5]:
x2[:5]

array([1.        , 1.08796759, 1.16933611, 1.2453997 , 1.31707778])

In [6]:
X = np.column_stack((x1, x2))
X[:5]

array([[1.        , 1.        ],
       [1.18367347, 1.08796759],
       [1.36734694, 1.16933611],
       [1.55102041, 1.2453997 ],
       [1.73469388, 1.31707778]])

In [7]:
X=sm.add_constant(X)
X[:5]

array([[1.        , 1.        , 1.        ],
       [1.        , 1.18367347, 1.08796759],
       [1.        , 1.36734694, 1.16933611],
       [1.        , 1.55102041, 1.2453997 ],
       [1.        , 1.73469388, 1.31707778]])

In [8]:
# b0,b1,b3
beta=[2,0.5,10]
#random error
e= np.random.normal(size = nsample)
#linear equation
y = np.dot(X,beta)+e

In [9]:
sample_df = pd.DataFrame({"y":y,"x1":x1,"x2":x2})
sample_df.head()

y        x1        x2
0  11.414369  1.000000  1.000000
1  14.468858  1.183673  1.087968
2  14.660013  1.367347  1.169336
3  13.723212  1.551020  1.245400
4  15.459524  1.734694  1.317078

In [10]:
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()
ax= Axes3D(fig)
ax.scatter3D(sample_df["y"],sample_df["x1"],sample_df["x2"])
plt.show()

<Figure size 640x480 with 0 Axes>

In [11]:
result=sm.OLS(y,X).fit()
print(result.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.976
Model:                            OLS   Adj. R-squared:                  0.975
Method:                 Least Squares   F-statistic:                     950.0
Date:                Mon, 13 Jan 2025   Prob (F-statistic):           9.87e-39
Time:                        16:31:24   Log-Likelihood:                -79.344
No. Observations:                  50   AIC:                             164.7
Df Residuals:                      47   BIC:                             170.4
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.5097      2.189      1.146      0.2

In [12]:
result.params

array([2.50973984, 0.70717503, 9.27757672])

In [13]:
result.bse

array([2.18915327, 0.49044175, 2.13130068])

In [14]:
result.tvalues

array([1.14644318, 1.44191442, 4.35301167])

In [15]:
result.pvalues

array([2.57415109e-01, 1.55957191e-01, 7.20355804e-05])